# Generated by Django 3.1 on 2021-01-18 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('des', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('mobileno', models.CharField(max_length=10)),
                ('pincode', models.CharField(default=1, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Orderdone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default=1, max_length=64)),
                ('item_price', models.CharField(default=1, max_length=64)),
                ('name', models.CharField(default=1, max_length=64)),
                ('mobile', models.CharField(default=1, max_length=64)),
                ('houseNo', models.CharField(default=1, max_length=64)),
                ('street', models.CharField(default=1, max_length=64)),
                ('session_name', models.CharField(default=1, max_length=64)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Swan_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=64)),
                ('price', models.CharField(default=1, max_length=64)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Swan_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=64)),
                ('price', models.CharField(default=1, max_length=64)),
                ('img', models.ImageField(default=1, upload_to='gallery')),
                ('weight', models.CharField(default=1, max_length=64)),
                ('weightunit', models.CharField(default=1, max_length=64)),
                ('description', models.CharField(default=1, max_length=64)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Swan_App.category')),
            ],
        ),
    ]
